spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mytest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: mytest
      password: 123456
  session:
    store-type: redis
    timeout: 300
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
