server:
  port: 8080

spring:
  application:
    name: bsf-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 30fd815f9df054a159b7
            client-secret: 043679e3a441d11a8a45858374310f3ff8c0292e

#security:
#  oauth2:
#    resource:
#      id: BSF
##      loadBalanced: true
##      prefer-token-info: true
##      user-info-uri: http://auth-server/oauth/check_token
#      service-id: auth-server
#      token-info-uri: http://auth-server/oauth/check_token
#    client:
#      client-id: resource1
#      client-secret: 1234567