server:
  port: 8081

spring:
  application:
    name: bsf-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
security:
  oauth2:
    resource:
      id: BSF
      loadBalanced: true
      prefer-token-info: true
      user-info-uri: http://auth-server/oauth/check_token
      service-id: auth-server
      token-info-uri: http://localhost:8080/oauth/check_token
    client:
      client-id: resource1
      client-secret: 1234567