server:
  port: 8081

spring:
  application:
    name: jsf-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  scan:
    base-packages: com.xgg.jsf.controller
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registries:
    new:
      address: spring-cloud://localhost
  consumer:
    check: false