server:
  port: 8080

spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    database: 0
    password: 123456
    port: 6379

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/xgg_pro?useUnicode=true&characterEncoding=utf8
      username: xggpro
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 10000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      filter:
        stat:
          enabled: true
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
        slf4j:
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        #        allow: 127.0.0.1
        #        deny: 192.168.0.19
        login-username: druid
        login-password: 123456
        reset-enable: true
        url-pattern: /druid/*

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.xgg.auth.pojo.entity

logging.level.org.springframework.security: DEBUG

xgg:
  auth:
    captcha:
      sms:
        interceptUrl: ""
        grantType: ""
      image:
        interceptUrl: ""
        grantType: ""

dubbo:
  scan:
    base-packages: com.xgg.auth.api.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registries:
    new:
      address: spring-cloud://localhost
  consumer:
    check: false