spring:
  session:
    store-type: redis
    timeout: 300
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.58.251:3306/mytest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: mytest
    password: 123456

server:
  port: 8081
  servlet:
    session:
      timeout: 30m